name: application
description: Application for controlling the smart car
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  flutter_joystick: ^0.0.3
  web_socket_channel: ^2.4.0
  webview_flutter: 4.2.2
  flutter_bluetooth_serial: ^0.4.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SelfDrivingCarIcons
      fonts:
        - asset: assets/fonts/SelfDrivingCarIcons.ttf

  assets:
    - assets/valjda_dobro.tflite