# See: https://www.dartlang.org/tools/pub/pubspec
name: flutter_opencv
version: 0.0.4
description: >-
  Flutter plugin for the OpenCV open-source computer vision library.
author: Arto Bendiken <arto@bendiken.net>
homepage: https://github.com/drydart/flutter_opencv

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  vector_math: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.3.4 <2.0.0'

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter:
  plugin:
    androidPackage: com.github.drydart.flutter_opencv
    pluginClass: FlutterOpenCVPlugin
