/// Flutter icons SelfDrivingCarIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SelfDrivingCarIcons
///      fonts:
///       - asset: fonts/SelfDrivingCarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SelfDrivingCarIcons {
  SelfDrivingCarIcons._();

  static const _kFontFam = 'SelfDrivingCarIcons';
  static const String? _kFontPkg = null;

  static const IconData manuallights = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hazard = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manualdrive = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beamlightsoff = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beamlights = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autolights = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autodrive = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
